Models/CodeAcces.cs
namespace GenerateurCodes.MVC.Models
{
    public class CodeAcces
    {
        public int Id { get; set; }

       public string NomDemandeur { get; set; }

       public DateTime DateExpiration { get; set; }

       public string Code { get; set; }

    }
}

Models/DemandeCodeAcces.cs
using System.ComponentModel.DataAnnotations;

namespace GenerateurCodes.MVC.Models
{
    public class DemandeCodeAcces
    {
        public int Id { get; set; }

        [MinLength(2, ErrorMessage ="Le nom doit avoir minimun 2 caractères")]
        [Display(Name = "Nom du demandeur")]
        [Required(ErrorMessage = "Le nom du demandeur est obligatoire")]
        public string NomDemandeur { get; set; }

        [Display(Name = "Date de naissance du demandeur")]
        [Required(ErrorMessage = "La date de naissance du demandeur est obligatoire")]
        public DateTime DateNaissanceDemandeur { get; set; }

        [Required(ErrorMessage ="Le NAS est obligatoire")]
        [Range(100000000,999999999, ErrorMessage ="Le NAS doit contenir 9 chiffres")]
        [Display(Name = "Numéro d'assurance sociale")]
        public int NAS { get; set; }

       public string RaisonDemande { get; set; }

    }
}

Models/ErrorViewModel.cs
namespace GenerateurCodes.MVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/GenerateurCodesController.cs
using GenerateurCodes.MVC.Data;
using GenerateurCodes.MVC.Interfaces;
using GenerateurCodes.MVC.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace GenerateurCodes.MVC.Controllers
{
    public class GenerateurCodesController : Controller
    {
        private readonly DataContext _context;

        public GenerateurCodesController(DataContext context)
        {
          _context = context;
        }
        // GET: GenerateurCodesController
        public async Task<ActionResult> Index()
        {
            //Retirer les commentaires pour vider la base de données si besoin
            //await _context.ReInitialiserBaseDeDonnees();
            return View();
        }


        // GET: GenerateurCodesController/Create
        public ActionResult ObtenirCode()
        {
            return View();
        }

        // POST: GenerateurCodesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ObtenirCode(DemandeCodeAcces demandeCodeAcces)
        {
            if(ModelState.IsValid)
            {
                //Sauvegarde de la demande dans la base de données
                _ = _context.InsererDemande(demandeCodeAcces);

                //Génération du code de sécurité du demandeur
                var code = GenererCode(demandeCodeAcces);

                var dateExpiration = DateTime.Now.AddMonths(6);

                //Sauvegarde du code de securité
                _ = _context.InsererCodeAcces(new CodeAcces
                {
                    DateExpiration = dateExpiration,
                    NomDemandeur = demandeCodeAcces.NomDemandeur,
                    Code = code
                });


                ViewBag.Resultat = $"Votre code d'accès est {code}. Il expire le {dateExpiration.ToLongDateString()}";
                
            }
            return View(demandeCodeAcces);
        }

        
        public ActionResult ValiderCode()
        {
            return View();
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ValiderCode(string nom, string code)
        {
            var codeAccess = await _context.ObtenirCodeAccess(nom);

            if (codeAccess.Any(c => c.Code == code && c.DateExpiration >= DateTime.Now))
                ViewBag.Message = "Votre code est valide";
            else
               ViewBag.Message = "Les informations fournies ne permettent pas d'obtenir un code valide"; 

          return View();
        }

        public async Task<ActionResult> ListerDemandes()
        {
            return View(await _context.ObtenirDemandeCodeAccess());

        }

        private string GenererCode(DemandeCodeAcces demandeCodeAcces)
        {
            //Premier caractère NAS
            var rnd = new Random();
            return  $"{demandeCodeAcces.NAS.ToString()[0]}-{demandeCodeAcces.NomDemandeur.Substring(0, 2)}-{demandeCodeAcces.DateNaissanceDemandeur.Year}-{rnd.Next(0000,9999)}-{demandeCodeAcces.NAS.ToString()[8]}";
        }
    }
}

Controllers/HomeController.cs
using GenerateurCodes.MVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace GenerateurCodes.MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/GenerateurCodes/Index.cshtml
@{
    ViewData["Title"] = "Générateur de code d'accès";
}

<div class="text-center">
    <h1 class="display-4">Générateur de code d'accès</h1>
    <br/>
    <p><a asp-action="ObtenirCode">Obtenir un code d'accès</a></p>
    <br/>
    <p><a asp-action="ValiderCode">Valider un code d'accès</a></p>
    <br/>
    <p><a asp-action="ListerDemandes">Consulter les demandes</a></p>
</div>

Views/GenerateurCodes/ListerDemandes.cshtml
@model IEnumerable<GenerateurCodes.MVC.Models.DemandeCodeAcces>

@{
    ViewData["Title"] = "ListerDemandes";
}

<h1>Demandes de code d'accès</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NomDemandeur)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateNaissanceDemandeur)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NAS)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RaisonDemande)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.Raw(item.Id)
            </td>
            <td>
                @Html.Raw(item.NomDemandeur)
            </td>
            <td>
                    @Html.Raw(item.DateNaissanceDemandeur)
            </td>
            <td>
                    @Html.Raw(item.NAS)
            </td>
            <td>
                    @Html.Raw(item.RaisonDemande)
            </td>
            
        </tr>
}
    </tbody>
</table>
<p>
    <a asp-controller="GenerateurCodes" asp-action="Index">Retourner au menu</a>
</p>

Views/GenerateurCodes/ObtenirCode.cshtml
@model GenerateurCodes.MVC.Models.DemandeCodeAcces

@{
    ViewData["Title"] = "ObtenirCode";
}

<h1>Demande d'un code d'accès</h1>

<h4>Veuillez remplir tous les champs</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        
        <p class="text-success">@ViewBag.Resultat</p>
       
        <form asp-action="ObtenirCode">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NomDemandeur" class="control-label"></label>
                <input asp-for="NomDemandeur" class="form-control" />
                <span asp-validation-for="NomDemandeur" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateNaissanceDemandeur" class="control-label"></label>
                <input asp-for="DateNaissanceDemandeur" type="date" class="form-control" />
                <span asp-validation-for="DateNaissanceDemandeur" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NAS" class="control-label"></label>
                <input asp-for="NAS" class="form-control" />
                <span asp-validation-for="NAS" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <label asp-for="RaisonDemande" class="control-label"></label>
                <textarea asp-for="RaisonDemande"></textarea>
                <span asp-validation-for="RaisonDemande" class="text-danger"></span>
            </div>
            <br/>
            <div class="form-group">
                <input type="submit" value="Envoyer la demande" class="btn btn-primary" />
                <a asp-controller="GenerateurCodes" asp-action="Index">Retourner au menu</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/GenerateurCodes/ValiderCode.cshtml


@{
    ViewData["Title"] = "Valider Code";
}

<h1>Valider Code d'accès</h1>
<hr />
<div class="row">
    <div class="col-md-4">
         <p class="text-success">@ViewBag.Message</p>
        <form asp-action="ValiderCode">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label class="control-label">Entrer votre nom</label>
                <input type="text" name="nom" id="nom" required class="form-control" />
            </div>
            <div class="form-group">
                <label class="control-label">Entrer votre code</label>
                <input type="text" name="code" id="code" required  class="form-control" /> 
            </div>
            <br/>
            <div class="form-group">
                <input type="submit" value="Valider le code" class="btn btn-primary" />
                <a asp-controller="GenerateurCodes" asp-action="Index">Retourner au menu</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GenerateurCodes.MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GenerateurCodes.MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GenerateurCodes.MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="GenerateurCodes" asp-action="Index">Générateur de codes</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - GenerateurCodes.MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>